import { createElement } from 'lwc';
import PathCaseStatusSupport360 from 'c/pathCaseStatusSupport360';

describe('c-path-case-status-support360', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-path-case-status-support360', {
            is: PathCaseStatusSupport360
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});